### ISSUE TITLE
Tests fails with Reform 2.1.0

### ISSUE THREAD

**Issue by acaron** [apotonick/tyrant#5]
Ruby 2.2.3 and Disposable 0.2.4

```
/Users/acaron/.rvm/gems/ruby-2.2.3/gems/disposable-0.2.4/lib/disposable/twin/definitions.rb:1:in `<top (required)>': uninitialized constant Disposable (NameError)
    from /Users/acaron/.rvm/gems/ruby-2.2.3/gems/disposable-0.2.4/lib/disposable/twin.rb:3:in `require'
    from /Users/acaron/.rvm/gems/ruby-2.2.3/gems/disposable-0.2.4/lib/disposable/twin.rb:3:in `<top (required)>'
    from /Users/acaron/Sites/tyrant/lib/tyrant.rb:7:in `require'
    from /Users/acaron/Sites/tyrant/lib/tyrant.rb:7:in `<top (required)>'
    from /Users/acaron/Sites/tyrant/test/test_helper.rb:2:in `require'
    from /Users/acaron/Sites/tyrant/test/test_helper.rb:2:in `<top (required)>'
    from /Users/acaron/Sites/tyrant/test/authenticatable_test.rb:1:in `require'
    from /Users/acaron/Sites/tyrant/test/authenticatable_test.rb:1:in `<top (required)>'
    from /Users/acaron/.rvm/gems/ruby-2.2.3/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `require'
    from /Users/acaron/.rvm/gems/ruby-2.2.3/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
    from /Users/acaron/.rvm/gems/ruby-2.2.3/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
    from /Users/acaron/.rvm/gems/ruby-2.2.3/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test:lib" -I"/Users/acaron/.rvm/gems/ruby-2.2.3/gems/rake-10.5.0/lib" "/Users/acaron/.rvm/gems/ruby-2.2.3/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/authenticatable_test.rb" "test/session_test.rb" "test/sign_up_test.rb" "test/tyrant_test.rb" ]
/Users/acaron/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/acaron/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by acaron** [comment]
Actually, it seems like it is Reform the problem. Working with 2.0.0.rc2 but not 2.1.0.

This is working:

```
GEM
  remote: https://rubygems.org/
  specs:
    activemodel (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    bcrypt (3.1.10)
    builder (3.2.2)
    disposable (0.1.15)
      representable (>= 2.2.3, < 2.4.0)
      uber
    i18n (0.7.0)
    json (1.8.3)
    minitest (5.8.3)
    rack (1.6.4)
    rake (10.5.0)
    reform (2.0.0.rc2)
      disposable (~> 0.1.5)
      uber (~> 0.0.11)
    representable (2.3.0)
      uber (~> 0.0.7)
    thread_safe (0.3.5)
    trailblazer (1.0.4)
      reform (>= 1.2.0)
      uber (>= 0.0.15)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uber (0.0.15)
    warden (1.2.4)
      rack (>= 1.0)
```
